import{A as y,S as L,N as b,P as S,i as w,a as u}from"./assets/vendor-70682666.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const E=document.querySelector(".name-list-menu"),q=document.querySelector(".backdrop-for-btn-menu");E.addEventListener("click",k);function k(){q.classList.toggle("is-open-for-btn-menu")}(()=>{const e=document.querySelector(".backdrop"),o=document.querySelector(".btn-open-burger"),r=document.querySelector("#menu-modal-close"),a=document.querySelector("#js-close-menu-1"),t=document.querySelector("#js-close-menu-3"),s=document.querySelector("#js-close-menu-2"),l=document.querySelector("#js-close-menu-4"),c=()=>{const p=o.getAttribute("aria-expanded")==="true"||!1;o.setAttribute("aria-expanded",!p),e.classList.toggle("is-open")};o.addEventListener("click",c),r.addEventListener("click",c),a.addEventListener("click",c),s.addEventListener("click",c),t.addEventListener("click",c),l.addEventListener("click",c),window.matchMedia("(min-width: 375px)").addEventListener("change",p=>{p.matches&&(e.classList.remove("is-open"),o.setAttribute("aria-expanded",!1))})})();new y(".accord-container",{openOnInit:[0]});new L(".swiper",{modules:[b,S]});new y(".faq-accordion-container");const M=document.querySelector(".feedback-list");async function j(){u.defaults.baseURL="https://portfolio-js.b.goit.study";try{return(await u.get("/api/reviews")).data}catch(e){console.log(e)}}j().then(e=>{e.length===0?w.error({message:"Not found"}):(console.log(e),x(e))});function x(e){const o=e.map(r=>`<li class="reviews-list"><div class="swiper-reviews">
            <div class="swiper-wrapper">
            <div class="swiper-slide">
                <img class="reviews-img" 
                    src="${r.avatar_url}" alt="Natalia" width="48" height="48">
                <h3 class="reviews-list-title">
                    ${r.author}
                </h3>
                <p class="reviews-list-text">
                    ${r.review}
                </p>
                </div>
                </div>
                </div>
                </li>`).join("");M.insertAdjacentHTML("beforeend",o)}new L(".swiper-reviews",{direction:"vertical",loop:!0,pagination:{el:".swiper-pagination"},navigation:{nextEl:".swiper-btn-last",prevEl:".swiper-btn-next"},breakpointsBase:"window"});const n=document.querySelector("#work-together-input-email"),A=document.querySelector("#work-together-input-comments"),f=document.querySelector(".email-succes"),v=document.querySelector(".email-invalid"),g=document.querySelector(".footer-form"),d=document.querySelector(".modal-backdrop-footer"),O=document.querySelector(".modal-footer"),m="work-together";let i={email:"",comments:""};u.defaults.baseURL="https://portfolio-js.b.goit.study";if(localStorage.getItem(m)){const e=localStorage.getItem(m);i=JSON.parse(e),A.value=i.comments,n.value=i.email}n.addEventListener("input",h);n.addEventListener("focus",h);g.addEventListener("input",B);g.addEventListener("submit",F);n.addEventListener("blur",e=>{e.preventDefault(),f.classList.add("visually-hidden"),v.classList.add("visually-hidden"),n.classList.remove("input-succes-js"),n.classList.remove("input-invalid-js")});function h(e){e.preventDefault(),f.classList.add("visually-hidden"),v.classList.add("visually-hidden"),n.classList.remove("input-succes-js"),n.classList.remove("input-invalid-js"),e.target.value.toLowerCase().match(/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{3,}))$/)?(f.classList.remove("visually-hidden"),n.classList.add("input-succes-js")):(v.classList.remove("visually-hidden"),n.classList.add("input-invalid-js"))}function B(e){e.preventDefault(),e.target.name==="client-email"?i.email=e.target.value.trim():e.target.name==="client-comments"&&(i.comments=e.target.value.trim()),localStorage.setItem(m,JSON.stringify(i))}async function F(e){e.preventDefault(),await u.post("/api/requests",{email:i.email,comment:i.comments}).then(function(o){localStorage.removeItem(m),g.reset(),i={email:"",comments:""};const r=document.querySelector(".modal-footer-title"),a=document.querySelector(".modal-footer-text");r.remove(),a.remove();const t=`
        <p class="modal-footer-title">${o.data.title}</p>
            <p class="modal-footer-text">${o.data.message}</p>
        `;O.insertAdjacentHTML("beforeend",t),d.classList.remove("modal-backdrop-footer-closed"),d.addEventListener("click",I),document.addEventListener("keydown",s=>{s.key==="Escape"&&d.classList.add("modal-backdrop-footer-closed")})}).catch(function(o){console.log(o),w.error({title:"Error",message:"Something went wrong",position:"center"})})}function I(e){e.preventDefault(),d.classList.add("modal-backdrop-footer-closed")}
//# sourceMappingURL=commonHelpers.js.map
